name: Check Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      desc:
        description: "desc"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'factoriotools/factorio-docker')

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Run update script
        run: ./update.sh
        shell: bash
